version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/app
        ports:
            - "6969:8000"
        networks:
            - cluster
        container_name: app

    db:
        image: mysql
        ports:
            - '${DB_PORT:-3306}:3306'
        restart: always
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        container_name: db

networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

