services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/app
        ports:
            - "6969:8000"
        networks:
            - cluster
        container_name: ${APP_NAME}_app

    db:
        image: mysql
        ports:
            - '3369:3306'
        restart: always
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        networks:
            - cluster
        container_name: ${APP_NAME}_db

networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

